In [1]:
import numpy as np 
import pandas as pd
import os

In [2]:
print(os.listdir('/kaggle/input/kdd-cup-1999-data'))

['kddcup.data.gz', 'kddcup.data', 'kddcup.testdata.unlabeled', 'training_attack_types', 'kddcup.data.corrected', 'kddcup.newtestdata_10_percent_unlabeled.gz', 'corrected', 'kddcup.testdata.unlabeled.gz', 'kddcup.testdata.unlabeled_10_percent', 'corrected.gz', 'kddcup.newtestdata_10_percent_unlabeled', 'kddcup.data_10_percent.gz', 'kddcup.names', 'kddcup.data_10_percent_corrected', 'typo-correction.txt', 'kddcup.data_10_percent', 'kddcup.testdata.unlabeled_10_percent.gz']


In [3]:
with open("/kaggle/input/kdd-cup-1999-data/kddcup.names",'r') as f:
    content = f.read()
    print(content)

back,buffer_overflow,ftp_write,guess_passwd,imap,ipsweep,land,loadmodule,multihop,neptune,nmap,normal,perl,phf,pod,portsweep,rootkit,satan,smurf,spy,teardrop,warezclient,warezmaster.
duration: continuous.
protocol_type: symbolic.
service: symbolic.
flag: symbolic.
src_bytes: continuous.
dst_bytes: continuous.
land: symbolic.
wrong_fragment: continuous.
urgent: continuous.
hot: continuous.
num_failed_logins: continuous.
logged_in: symbolic.
num_compromised: continuous.
root_shell: continuous.
su_attempted: continuous.
num_root: continuous.
num_file_creations: continuous.
num_shells: continuous.
num_access_files: continuous.
num_outbound_cmds: continuous.
is_host_login: symbolic.
is_guest_login: symbolic.
count: continuous.
srv_count: continuous.
serror_rate: continuous.
srv_serror_rate: continuous.
rerror_rate: continuous.
srv_rerror_rate: continuous.
same_srv_rate: continuous.
diff_srv_rate: continuous.
srv_diff_host_rate: continuous.
dst_host_count: continuous.
dst_host_srv_count: con

In [5]:
cols = []
content = content.split("\n")[1:]
for c in content:
    if len(c) > 1:
        print(c.split(":")[0])
        cols.append(c.split(":")[0])
cols.append("target")

duration
protocol_type
service
flag
src_bytes
dst_bytes
land
wrong_fragment
urgent
hot
num_failed_logins
logged_in
num_compromised
root_shell
su_attempted
num_root
num_file_creations
num_shells
num_access_files
num_outbound_cmds
is_host_login
is_guest_login
count
srv_count
serror_rate
srv_serror_rate
rerror_rate
srv_rerror_rate
same_srv_rate
diff_srv_rate
srv_diff_host_rate
dst_host_count
dst_host_srv_count
dst_host_same_srv_rate
dst_host_diff_srv_rate
dst_host_same_src_port_rate
dst_host_srv_diff_host_rate
dst_host_serror_rate
dst_host_srv_serror_rate
dst_host_rerror_rate
dst_host_srv_rerror_rate


In [6]:
cols


['duration',
 'protocol_type',
 'service',
 'flag',
 'src_bytes',
 'dst_bytes',
 'land',
 'wrong_fragment',
 'urgent',
 'hot',
 'num_failed_logins',
 'logged_in',
 'num_compromised',
 'root_shell',
 'su_attempted',
 'num_root',
 'num_file_creations',
 'num_shells',
 'num_access_files',
 'num_outbound_cmds',
 'is_host_login',
 'is_guest_login',
 'count',
 'srv_count',
 'serror_rate',
 'srv_serror_rate',
 'rerror_rate',
 'srv_rerror_rate',
 'same_srv_rate',
 'diff_srv_rate',
 'srv_diff_host_rate',
 'dst_host_count',
 'dst_host_srv_count',
 'dst_host_same_srv_rate',
 'dst_host_diff_srv_rate',
 'dst_host_same_src_port_rate',
 'dst_host_srv_diff_host_rate',
 'dst_host_serror_rate',
 'dst_host_srv_serror_rate',
 'dst_host_rerror_rate',
 'dst_host_srv_rerror_rate',
 'target']

In [7]:
len(cols)


42

# Preparing the dataset

In [9]:
training_data=pd.read_csv("/kaggle/input/kdd-cup-1999-data/kddcup.data_10_percent.gz",names=cols)

In [10]:
testing_data=pd.read_csv("/kaggle/input/kdd-cup-1999-data/corrected.gz",names=cols)

In [11]:
len(training_data)

494021

In [12]:
len(testing_data)

311029

In [13]:
training_data

duration protocol_type service flag  src_bytes  dst_bytes  land  \
0              0           tcp    http   SF        181       5450     0   
1              0           tcp    http   SF        239        486     0   
2              0           tcp    http   SF        235       1337     0   
3              0           tcp    http   SF        219       1337     0   
4              0           tcp    http   SF        217       2032     0   
...          ...           ...     ...  ...        ...        ...   ...   
494016         0           tcp    http   SF        310       1881     0   
494017         0           tcp    http   SF        282       2286     0   
494018         0           tcp    http   SF        203       1200     0   
494019         0           tcp    http   SF        291       1200     0   
494020         0           tcp    http   SF        219       1234     0   

        wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                    0       0    0  ...                   9   
1                    0       0    0  ...                  19   
2                    0       0    0  ...                  29   
3                    0       0    0  ...                  39   
4                    0       0    0  ...                  49   
...                ...     ...  ...  ...                 ...   
494016               0       0    0  ...                 255   
494017               0       0    0  ...                 255   
494018               0       0    0  ...                 255   
494019               0       0    0  ...                 255   
494020               0       0    0  ...                 255   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                          1.0                     0.0   
1                          1.0                     0.0   
2                          1.0                     0.0   
3                          1.0                     0.0   
4                          1.0                     0.0   
...                        ...                     ...   
494016                     1.0                     0.0   
494017                     1.0                     0.0   
494018                     1.0                     0.0   
494019                     1.0                     0.0   
494020                     1.0                     0.0   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.11                         0.00   
1                              0.05                         0.00   
2                              0.03                         0.00   
3                              0.03                         0.00   
4                              0.02                         0.00   
...                             ...                          ...   
494016                         0.01                         0.05   
494017                         0.17                         0.05   
494018                         0.06                         0.05   
494019                         0.04                         0.05   
494020                         0.17                         0.05   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                       0.00                      0.00                   0.0   
1                       0.00                      0.00                   0.0   
2                       0.00                      0.00                   0.0   
3                       0.00                      0.00                   0.0   
4                       0.00                      0.00                   0.0   
...                      ...                       ...                   ...   
494016                  0.00                      0.01                   0.0   
494017                  0.00                      0.01                   0.0   
494018                  0.06                      0.01                   0.0   
494019                  

In [14]:
testing_data

duration protocol_type  service flag  src_bytes  dst_bytes  land  \
0              0           udp  private   SF        105        146     0   
1              0           udp  private   SF        105        146     0   
2              0           udp  private   SF        105        146     0   
3              0           udp  private   SF        105        146     0   
4              0           udp  private   SF        105        146     0   
...          ...           ...      ...  ...        ...        ...   ...   
311024         0           udp  private   SF        105        147     0   
311025         0           udp  private   SF        105        147     0   
311026         0           udp  private   SF        105        147     0   
311027         0           udp  private   SF        105        147     0   
311028         0           udp  private   SF        105        147     0   

        wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                    0       0    0  ...                 254   
1                    0       0    0  ...                 254   
2                    0       0    0  ...                 254   
3                    0       0    0  ...                 254   
4                    0       0    0  ...                 254   
...                ...     ...  ...  ...                 ...   
311024               0       0    0  ...                 255   
311025               0       0    0  ...                 255   
311026               0       0    0  ...                 255   
311027               0       0    0  ...                 255   
311028               0       0    0  ...                 255   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                          1.0                    0.01   
1                          1.0                    0.01   
2                          1.0                    0.01   
3                          1.0                    0.01   
4                          1.0                    0.01   
...                        ...                     ...   
311024                     1.0                    0.00   
311025                     1.0                    0.00   
311026                     1.0                    0.00   
311027                     1.0                    0.00   
311028                     1.0                    0.00   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.00                          0.0   
1                              0.00                          0.0   
2                              0.00                          0.0   
3                              0.00                          0.0   
4                              0.01                          0.0   
...                             ...                          ...   
311024                         0.01                          0.0   
311025                         0.01                          0.0   
311026                         0.01                          0.0   
311027                         0.01                          0.0   
311028                         0.01                          0.0   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                        0.0                       0.0                   0.0   
1                        0.0                       0.0                   0.0   
2                        0.0                       0.0                   0.0   
3                        0.0                       0.0                   0.0   
4                        0.0                       0.0                   0.0   
...                      ...                       ...                   ...   
311024                   0.0                       0.0                   0.0   
311025                   0.0                       0.0                   0.0   
311026                   0.0                       0.0                   0.0   
311027      

In [19]:
len(training_data['target'].value_counts())

23

In [18]:
len(training_data['target'].value_counts())

38

In [20]:
training_data.dtypes

duration                         int64
protocol_type                   object
service                         object
flag                            object
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate          

In [27]:
training_data['target'].unique()

array(['normal.', 'buffer_overflow.', 'loadmodule.', 'perl.', 'neptune.',
       'smurf.', 'guess_passwd.', 'pod.', 'teardrop.', 'portsweep.',
       'ipsweep.', 'land.', 'ftp_write.', 'back.', 'imap.', 'satan.',
       'phf.', 'nmap.', 'multihop.', 'warezmaster.', 'warezclient.',
       'spy.', 'rootkit.'], dtype=object)

In [26]:
testing_data['target'].unique()

array(['normal.', 'snmpgetattack.', 'named.', 'xlock.', 'smurf.',
       'ipsweep.', 'multihop.', 'xsnoop.', 'sendmail.', 'guess_passwd.',
       'saint.', 'buffer_overflow.', 'portsweep.', 'pod.', 'apache2.',
       'phf.', 'udpstorm.', 'warezmaster.', 'perl.', 'satan.', 'xterm.',
       'mscan.', 'processtable.', 'ps.', 'nmap.', 'rootkit.', 'neptune.',
       'loadmodule.', 'imap.', 'back.', 'httptunnel.', 'worm.',
       'mailbomb.', 'ftp_write.', 'teardrop.', 'land.', 'sqlattack.',
       'snmpguess.'], dtype=object)

In [113]:
from sklearn.preprocessing import LabelEncoder
def encode_and_split(training_df,testing_df):
    #1-drop in-consistent targets in testing_data
    
    # create a list of values to keep
    my_list = training_df['target'].unique()

    # drop rows with values in column 'target' that are not in the list
    df_filtered = testing_df.loc[testing_df['target'].isin(my_list)]


    
    
    
    #get length of training and testing to split after encoding
    train_size=len(training_df)
    test_size=len(df_filtered)
    
    # concatenate the two data frames vertically to encode them
    concatenated_df = pd.concat([training_df, testing_df])
    
    
    #label encode targets
    
    # create a label encoder object
    le = LabelEncoder()

    # fit the label encoder to the 'target' column in the data frame
    le.fit(concatenated_df['target'])
    
    # transform the 'target' column using the label encoder
    concatenated_df['target_encoded'] = le.transform(concatenated_df['target'])

    #one hot encode
    concatenated_df=pd.get_dummies(concatenated_df, columns=['protocol_type','service','flag'])
    
    concatenated_df=concatenated_df.drop('target',axis=1)
    
    #split into training , testing 
    training_df=concatenated_df.iloc[:train_size]
    testing_df=concatenated_df.iloc[train_size:]
    
    
    return training_df,testing_df
    
    



In [149]:
from sklearn.preprocessing import LabelEncoder
def encode_and_split(training_df,testing_df):
    #1-drop in-consistent targets in testing_data
    
    # create a list of values to keep
    my_list = training_df['target'].unique()

    # drop rows with values in column 'target' that are not in the list
    df_filtered = testing_df.loc[testing_df['target'].isin(my_list)]


    
    
    
    #get length of training and testing to split after encoding
    train_size=len(training_df)
    test_size=len(df_filtered)
    
    # concatenate the two data frames vertically to encode them
    concatenated_df = pd.concat([training_df, testing_df])
    
    
    #label encode targets
    
    # create a label encoder object
    le = LabelEncoder()


    # Encode the 'color' and 'size' columns in the dataframe
    concatenated_df['protocol_type'] = le.fit_transform(concatenated_df['protocol_type'])
    concatenated_df['service'] = le.fit_transform(concatenated_df['service'])
    concatenated_df['flag'] = le.fit_transform(concatenated_df['flag'])
    concatenated_df['target_encoded'] = le.fit_transform(concatenated_df['target'])

    concatenated_df=concatenated_df.drop('target',axis=1)

    
    #split into training , testing 
    training_df=concatenated_df.iloc[:train_size]
    testing_df=concatenated_df.iloc[train_size:]
    
    
    return training_df,testing_df
    
    



In [150]:
training_df,testing_df=encode_and_split(training_data,testing_data)

In [152]:
training_df

duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0              0              1       22     9        181       5450     0   
1              0              1       22     9        239        486     0   
2              0              1       22     9        235       1337     0   
3              0              1       22     9        219       1337     0   
4              0              1       22     9        217       2032     0   
...          ...            ...      ...   ...        ...        ...   ...   
494016         0              1       22     9        310       1881     0   
494017         0              1       22     9        282       2286     0   
494018         0              1       22     9        203       1200     0   
494019         0              1       22     9        291       1200     0   
494020         0              1       22     9        219       1234     0   

        wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                    0       0    0  ...                   9   
1                    0       0    0  ...                  19   
2                    0       0    0  ...                  29   
3                    0       0    0  ...                  39   
4                    0       0    0  ...                  49   
...                ...     ...  ...  ...                 ...   
494016               0       0    0  ...                 255   
494017               0       0    0  ...                 255   
494018               0       0    0  ...                 255   
494019               0       0    0  ...                 255   
494020               0       0    0  ...                 255   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                          1.0                     0.0   
1                          1.0                     0.0   
2                          1.0                     0.0   
3                          1.0                     0.0   
4                          1.0                     0.0   
...                        ...                     ...   
494016                     1.0                     0.0   
494017                     1.0                     0.0   
494018                     1.0                     0.0   
494019                     1.0                     0.0   
494020                     1.0                     0.0   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.11                         0.00   
1                              0.05                         0.00   
2                              0.03                         0.00   
3                              0.03                         0.00   
4                              0.02                         0.00   
...                             ...                          ...   
494016                         0.01                         0.05   
494017                         0.17                         0.05   
494018                         0.06                         0.05   
494019                         0.04                         0.05   
494020                         0.17                         0.05   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                       0.00                      0.00                   0.0   
1                       0.00                      0.00                   0.0   
2                       0.00                      0.00                   0.0   
3                       0.00                      0.00                   0.0   
4                       0.00                      0.00                   0.0   
...                      ...                       ...                   ...   
494016                  0.00                      0.01                   0.0   
494017                  0.00                      0.01                   0.0   
494018                  0.06                      0.01              

In [153]:
testing_df

duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0              0              2       46     9        105        146     0   
1              0              2       46     9        105        146     0   
2              0              2       46     9        105        146     0   
3              0              2       46     9        105        146     0   
4              0              2       46     9        105        146     0   
...          ...            ...      ...   ...        ...        ...   ...   
311024         0              2       46     9        105        147     0   
311025         0              2       46     9        105        147     0   
311026         0              2       46     9        105        147     0   
311027         0              2       46     9        105        147     0   
311028         0              2       46     9        105        147     0   

        wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                    0       0    0  ...                 254   
1                    0       0    0  ...                 254   
2                    0       0    0  ...                 254   
3                    0       0    0  ...                 254   
4                    0       0    0  ...                 254   
...                ...     ...  ...  ...                 ...   
311024               0       0    0  ...                 255   
311025               0       0    0  ...                 255   
311026               0       0    0  ...                 255   
311027               0       0    0  ...                 255   
311028               0       0    0  ...                 255   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                          1.0                    0.01   
1                          1.0                    0.01   
2                          1.0                    0.01   
3                          1.0                    0.01   
4                          1.0                    0.01   
...                        ...                     ...   
311024                     1.0                    0.00   
311025                     1.0                    0.00   
311026                     1.0                    0.00   
311027                     1.0                    0.00   
311028                     1.0                    0.00   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.00                          0.0   
1                              0.00                          0.0   
2                              0.00                          0.0   
3                              0.00                          0.0   
4                              0.01                          0.0   
...                             ...                          ...   
311024                         0.01                          0.0   
311025                         0.01                          0.0   
311026                         0.01                          0.0   
311027                         0.01                          0.0   
311028                         0.01                          0.0   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                        0.0                       0.0                   0.0   
1                        0.0                       0.0                   0.0   
2                        0.0                       0.0                   0.0   
3                        0.0                       0.0                   0.0   
4                        0.0                       0.0                   0.0   
...                      ...                       ...                   ...   
311024                   0.0                       0.0                   0.0   
311025                   0.0                       0.0                   0.0   
311026                   0.0                       0.0              

# Clustering Using K-Means 

In [154]:
#split the data
X_train=training_df.drop('target_encoded',axis=1).values
y_train=training_df['target_encoded'].values

X_test=testing_df.drop('target_encoded',axis=1).values
y_test=testing_df['target_encoded'].values


In [155]:
X_train.shape

(494021, 41)

In [156]:
y_train.shape

(494021,)

In [157]:
np.unique(y_train)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 12, 14, 15, 16, 17, 18, 19, 20, 23,
       25, 27, 30, 32, 34, 35])

In [121]:
class KMeans:
    def __init__(self, n_clusters=8, max_iter=300):
        self.n_clusters = n_clusters
        self.max_iter = max_iter
        self.centroids = None

    def fit(self, X):
        # Initialize centroids randomly
        self.centroids = X[np.random.choice(X.shape[0], size=self.n_clusters, replace=False), :]

        for i in range(self.max_iter):
            # Assign each point to the nearest centroid
            distances = np.sqrt(((X - self.centroids[:, np.newaxis])**2).sum(axis=2))
            labels = np.argmin(distances, axis=0)

            # Update the centroids to the mean of each cluster
            for j in range(self.n_clusters):
                if np.sum(labels == j) == 0:
                    continue
                self.centroids[j, :] = np.mean(X[labels == j, :], axis=0)

    def predict(self, X):
        distances = np.sqrt(((X - self.centroids[:, np.newaxis])**2).sum(axis=2))
        labels = np.argmin(distances, axis=0)
        return labels


In [100]:
kmeans = KMeans(n_clusters=23)
kmeans.fit(X_train)

# predict labels for new data
labels = kmeans.predict(X_test)

print(labels)




[3 3 3 ... 3 3 3]


In [106]:
labels

array([3, 3, 3, ..., 3, 3, 3])

In [107]:
y_test

array([16, 16, 16, ..., 16, 16, 16])

In [101]:
np.unique(labels)

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [102]:
np.unique(y_test)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 35,
       36, 37, 38, 39])

In [103]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, labels)


In [104]:
accuracy


0.010815711718199911

In [163]:
from sklearn.preprocessing import StandardScaler
# Create a StandardScaler instance to normalize the data
scaler = StandardScaler()

# Normalize the data
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)


In [164]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=23, random_state=0)

# Fit the data to the KMeans model
kmeans.fit(X_train)

# Print the centroids of the trained KMeans model

labels = kmeans.predict(X_test)

# print(labels)


print(accuracy_score(y_test, labels))

0.0009838310897054615


In [160]:
y_test[0:16]

array([16, 16, 16, 28, 28, 28, 16, 16, 28, 16, 28, 16, 16, 28, 16, 16])

In [161]:
labels[0:16]

array([19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,  0, 14],
      dtype=int32)

In [165]:
from sklearn.metrics import adjusted_rand_score

# Instantiate KMeans object and fit to data
kmeans = KMeans(n_clusters=4, init='k-means++', max_iter=300, random_state=0)
kmeans.fit(X_train)

# Calculate the Adjusted Rand Index (ARI)
ari = adjusted_rand_score(y_train, kmeans.labels_)

# Print the ARI score
print("The Adjusted Rand Index (ARI) is:", ari)


The Adjusted Rand Index (ARI) is: 0.9472601233983616


In [167]:
len(kmeans.cluster_centers_)

4